# -*- coding: utf-8 -*-
"""Flowers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T4kI2iBKm3xdiJvZK36MQx2DvSiyqqAK

# Importing the libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR

"""# Importing the dataset and  Converting the flower names to numbers"""

df = pd.read_csv("iris.data", 
                  sep=',', 
                  names=[" sepal length", "sepal width", "petal length", "petal width","Flower Name"])
df.iloc[:,-1] = df.iloc[:,-1].replace(['Iris-setosa'], '0')
df.iloc[:,-1] = df.iloc[:,-1].replace(['Iris-versicolor'], '1')
df.iloc[:,-1] = df.iloc[:,-1].replace(['Iris-virginica'], '2')
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
y = np.reshape(y,(-1,1))
df

"""# Finding suitable model"""

scaler = StandardScaler()
scaler.fit(df.drop('Flower Name',axis=1))
scaled_features = scaler.transform(df.drop('Flower Name',axis=1))
scaler_trans = pd.DataFrame(scaled_features,columns=df.columns[:-1])
scaler_trans.head() 
import seaborn as sns
sns.pairplot(df,hue = 'Flower Name' )

"""# Splitting the the module"""

X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.3,random_state=0)

"""# Standard Scaling"""

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

"""# Fitting Logistic Regression Model to database"""

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

"""# Predicting new value"""

y_pred = classifier.predict(X_test)
y_pred = np.reshape(y_pred,(-1,1))
np.shape(y_pred)
y_pred 
y_test

"""# Making the Confusion Matrix"""

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)